<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'ZendCartDoctrineORM\Module'                               => __DIR__ . '/Module.php',
  'ZendCartDoctrineORM\Adapter\CartAdapterInterface'         => __DIR__ . '/src/ZendCartDoctrineORM/Adapter/CartAdapterInterface.php',
  'ZendCartDoctrineORM\Adapter\DoctrineCartAdapter'          => __DIR__ . '/src/ZendCartDoctrineORM/Adapter/DoctrineCartAdapter.php',
  'ZendCartDoctrineORM\Entity\Cart'                          => __DIR__ . '/src/ZendCartDoctrineORM/Entity/Cart.php',
  'ZendCartDoctrineORM\Entity\CartEntityInterface'           => __DIR__ . '/src/ZendCartDoctrineORM/Entity/CartEntityInterface.php',
  'ZendCartDoctrineORM\Entity\CartItem'                      => __DIR__ . '/src/ZendCartDoctrineORM/Entity/CartItem.php',
  'ZendCartDoctrineORM\Entity\CartItemInterface'             => __DIR__ . '/src/ZendCartDoctrineORM/Entity/CartItemInterface.php',
  'ZendCartDoctrineORM\Hydrator\CartItemHydrator'            => __DIR__ . '/src/ZendCartDoctrineORM/Hydrator/CartItemHydrator.php',
  'ZendCartDoctrineORM\Listener\CartListener'                => __DIR__ . '/src/ZendCartDoctrineORM/Listener/CartListener.php',
  'ZendCartDoctrineORM\Listener\Factory\CartListenerFactory' => __DIR__ . '/src/ZendCartDoctrineORM/Listener/Factory/CartListenerFactory.php',
  'ZendCartDoctrineORM\Service\CartService'                  => __DIR__ . '/src/ZendCartDoctrineORM/Service/CartService.php',
  'ZendCartDoctrineORM\Service\CartServiceInterface'         => __DIR__ . '/src/ZendCartDoctrineORM/Service/CartServiceInterface.php',
  'ZendCartDoctrineORM\Service\Factory\CartServiceFactory'   => __DIR__ . '/src/ZendCartDoctrineORM/Service/Factory/CartServiceFactory.php',
);
